# This file has been autogenerated by the pywayland scanner

# Copyright © 2019 Purism SPC
#
# Permission to use, copy, modify, distribute, and sell this
# software and its documentation for any purpose is hereby granted
# without fee, provided that the above copyright notice appear in
# all copies and that both that copyright notice and this permission
# notice appear in supporting documentation, and that the name of
# the copyright holders not be used in advertising or publicity
# pertaining to distribution of the software without specific,
# written prior permission.  The copyright holders make no
# representations about the suitability of this software for any
# purpose.  It is provided "as is" without express or implied
# warranty.
#
# THE COPYRIGHT HOLDERS DISCLAIM ALL WARRANTIES WITH REGARD TO THIS
# SOFTWARE, INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY AND
# FITNESS, IN NO EVENT SHALL THE COPYRIGHT HOLDERS BE LIABLE FOR ANY
# SPECIAL, INDIRECT OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES
# WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN
# AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION,
# ARISING OUT OF OR IN CONNECTION WITH THE USE OR PERFORMANCE OF
# THIS SOFTWARE.

from __future__ import annotations

import enum

from pywayland.protocol_core import Argument, ArgumentType, Global, Interface, Proxy, Resource


class ZwlrOutputConfigurationHeadV1(Interface):
    """Head configuration

    This object is used by the client to update a single head's configuration.

    It is a protocol error to set the same property twice.
    """

    name = "zwlr_output_configuration_head_v1"
    version = 4

    class error(enum.IntEnum):
        already_set = 1
        invalid_mode = 2
        invalid_custom_mode = 3
        invalid_transform = 4
        invalid_scale = 5
        invalid_adaptive_sync_state = 6


class ZwlrOutputConfigurationV1(Interface):
    """Output configuration

    This object is used by the client to describe a full output configuration.

    First, the client needs to setup the output configuration. Each head can be
    either enabled (and configured) or disabled. It is a protocol error to send
    two enable_head or disable_head requests with the same head. It is a
    protocol error to omit a head in a configuration.

    Then, the client can apply or test the configuration. The compositor will
    then reply with a succeeded, failed or cancelled event. Finally the client
    should destroy the configuration object.
    """

    name = "zwlr_output_configuration_v1"
    version = 4

    class error(enum.IntEnum):
        already_configured_head = 1
        unconfigured_head = 2
        already_used = 3


class ZwlrOutputHeadV1(Interface):
    """Output device

    A head is an output device. The difference between a
    :class:`~pywayland.protocol.wayland.WlOutput` object and a head is that
    heads are advertised even if they are turned off. A head object only
    advertises properties and cannot be used directly to change them.

    A head has some read-only properties: modes, name, description and
    physical_size. These cannot be changed by clients.

    Other properties can be updated via a wlr_output_configuration object.

    Properties sent via this interface are applied atomically via the
    wlr_output_manager.done event. No guarantees are made regarding the order
    in which properties are sent.
    """

    name = "zwlr_output_head_v1"
    version = 4

    class adaptive_sync_state(enum.IntEnum):
        disabled = 0
        enabled = 1


class ZwlrOutputManagerV1(Interface):
    """Output device configuration manager

    This interface is a manager that allows reading and writing the current
    output device configuration.

    Output devices that display pixels (e.g. a physical monitor or a virtual
    output in a window) are represented as heads. Heads cannot be created nor
    destroyed by the client, but they can be enabled or disabled and their
    properties can be changed. Each head may have one or more available modes.

    Whenever a head appears (e.g. a monitor is plugged in), it will be
    advertised via the head event. Immediately after the output manager is
    bound, all current heads are advertised.

    Whenever a head's properties change, the relevant wlr_output_head events
    will be sent. Not all head properties will be sent: only properties that
    have changed need to.

    Whenever a head disappears (e.g. a monitor is unplugged), a
    wlr_output_head.finished event will be sent.

    After one or more heads appear, change or disappear, the done event will be
    sent. It carries a serial which can be used in a create_configuration
    request to update heads properties.

    The information obtained from this protocol should only be used for output
    configuration purposes. This protocol is not designed to be a generic
    output property advertisement protocol for regular clients. Instead,
    protocols such as xdg-output should be used.
    """

    name = "zwlr_output_manager_v1"
    version = 4


class ZwlrOutputModeV1(Interface):
    """Output mode

    This object describes an output mode.

    Some heads don't support output modes, in which case modes won't be
    advertised.

    Properties sent via this interface are applied atomically via the
    wlr_output_manager.done event. No guarantees are made regarding the order
    in which properties are sent.
    """

    name = "zwlr_output_mode_v1"
    version = 3


class ZwlrOutputConfigurationHeadV1Resource(Resource[ZwlrOutputConfigurationHeadV1]):
    interface = ZwlrOutputConfigurationHeadV1


class ZwlrOutputConfigurationV1Resource(Resource[ZwlrOutputConfigurationV1]):
    interface = ZwlrOutputConfigurationV1

    @ZwlrOutputConfigurationV1.event()
    def succeeded(self) -> None:
        """Configuration changes succeeded

        Sent after the compositor has successfully applied the changes or
        tested them.

        Upon receiving this event, the client should destroy this object.

        If the current configuration has changed, events to describe the
        changes will be sent followed by a wlr_output_manager.done event.
        """
        self._post_event(0)

    @ZwlrOutputConfigurationV1.event()
    def failed(self) -> None:
        """Configuration changes failed

        Sent if the compositor rejects the changes or failed to apply them. The
        compositor should revert any changes made by the apply request that
        triggered this event.

        Upon receiving this event, the client should destroy this object.
        """
        self._post_event(1)

    @ZwlrOutputConfigurationV1.event()
    def cancelled(self) -> None:
        """Configuration has been cancelled

        Sent if the compositor cancels the configuration because the state of
        an output changed and the client has outdated information (e.g. after
        an output has been hotplugged).

        The client can create a new configuration with a newer serial and try
        again.

        Upon receiving this event, the client should destroy this object.
        """
        self._post_event(2)


class ZwlrOutputHeadV1Resource(Resource[ZwlrOutputHeadV1]):
    interface = ZwlrOutputHeadV1

    @ZwlrOutputHeadV1.event(
        Argument(ArgumentType.String),
    )
    def name(self, name: str) -> None:
        """Head name

        This event describes the head name.

        The naming convention is compositor defined, but limited to
        alphanumeric characters and dashes (-). Each name is unique among all
        wlr_output_head objects, but if a wlr_output_head object is destroyed
        the same name may be reused later. The names will also remain
        consistent across sessions with the same hardware and software
        configuration.

        Examples of names include 'HDMI-A-1', 'WL-1', 'X11-1', etc. However, do
        not assume that the name is a reflection of an underlying DRM
        connector, X11 connection, etc.

        If this head matches a :class:`~pywayland.protocol.wayland.WlOutput`,
        the :func:`WlOutput.name() <pywayland.protocol.wayland.WlOutput.name>`
        event must report the same name.

        The name event is sent after a wlr_output_head object is created. This
        event is only sent once per object, and the name does not change over
        the lifetime of the wlr_output_head object.

        :param name:
        :type name:
            `ArgumentType.String`
        """
        self._post_event(0, name)

    @ZwlrOutputHeadV1.event(
        Argument(ArgumentType.String),
    )
    def description(self, description: str) -> None:
        """Head description

        This event describes a human-readable description of the head.

        The description is a UTF-8 string with no convention defined for its
        contents. Examples might include 'Foocorp 11" Display' or 'Virtual X11
        output via :1'. However, do not assume that the name is a reflection of
        the make, model, serial of the underlying DRM connector or the display
        name of the underlying X11 connection, etc.

        If this head matches a :class:`~pywayland.protocol.wayland.WlOutput`,
        the :func:`WlOutput.description()
        <pywayland.protocol.wayland.WlOutput.description>` event must report
        the same name.

        The description event is sent after a wlr_output_head object is
        created. This event is only sent once per object, and the description
        does not change over the lifetime of the wlr_output_head object.

        :param description:
        :type description:
            `ArgumentType.String`
        """
        self._post_event(1, description)

    @ZwlrOutputHeadV1.event(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def physical_size(self, width: int, height: int) -> None:
        """Head physical size

        This event describes the physical size of the head. This event is only
        sent if the head has a physical size (e.g. is not a projector or a
        virtual device).

        The physical size event is sent after a wlr_output_head object is
        created. This event is only sent once per object, and the physical size
        does not change over the lifetime of the wlr_output_head object.

        :param width:
            width in millimeters of the output
        :type width:
            `ArgumentType.Int`
        :param height:
            height in millimeters of the output
        :type height:
            `ArgumentType.Int`
        """
        self._post_event(2, width, height)

    @ZwlrOutputHeadV1.event(
        Argument(ArgumentType.NewId, interface=ZwlrOutputModeV1),
    )
    def mode(self, mode: ZwlrOutputModeV1) -> None:
        """Introduce a mode

        This event introduces a mode for this head. It is sent once per
        supported mode.

        :param mode:
        :type mode:
            :class:`~pywayland.protocol.wlr_output_management_unstable_v1.ZwlrOutputModeV1`
        """
        self._post_event(3, mode)

    @ZwlrOutputHeadV1.event(
        Argument(ArgumentType.Int),
    )
    def enabled(self, enabled: int) -> None:
        """Head is enabled or disabled

        This event describes whether the head is enabled. A disabled head is
        not mapped to a region of the global compositor space.

        When a head is disabled, some properties (current_mode, position,
        transform and scale) are irrelevant.

        :param enabled:
            zero if disabled, non-zero if enabled
        :type enabled:
            `ArgumentType.Int`
        """
        self._post_event(4, enabled)

    @ZwlrOutputHeadV1.event(
        Argument(ArgumentType.Object, interface=ZwlrOutputModeV1),
    )
    def current_mode(self, mode: ZwlrOutputModeV1) -> None:
        """Current mode

        This event describes the mode currently in use for this head. It is
        only sent if the output is enabled.

        :param mode:
        :type mode:
            :class:`~pywayland.protocol.wlr_output_management_unstable_v1.ZwlrOutputModeV1`
        """
        self._post_event(5, mode)

    @ZwlrOutputHeadV1.event(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def position(self, x: int, y: int) -> None:
        """Current position

        This events describes the position of the head in the global compositor
        space. It is only sent if the output is enabled.

        :param x:
            x position within the global compositor space
        :type x:
            `ArgumentType.Int`
        :param y:
            y position within the global compositor space
        :type y:
            `ArgumentType.Int`
        """
        self._post_event(6, x, y)

    @ZwlrOutputHeadV1.event(
        Argument(ArgumentType.Int),
    )
    def transform(self, transform: int) -> None:
        """Current transformation

        This event describes the transformation currently applied to the head.
        It is only sent if the output is enabled.

        :param transform:
        :type transform:
            `ArgumentType.Int`
        """
        self._post_event(7, transform)

    @ZwlrOutputHeadV1.event(
        Argument(ArgumentType.Fixed),
    )
    def scale(self, scale: float) -> None:
        """Current scale

        This events describes the scale of the head in the global compositor
        space. It is only sent if the output is enabled.

        :param scale:
        :type scale:
            `ArgumentType.Fixed`
        """
        self._post_event(8, scale)

    @ZwlrOutputHeadV1.event()
    def finished(self) -> None:
        """The head has disappeared

        This event indicates that the head is no longer available. The head
        object becomes inert. Clients should send a destroy request and release
        any resources associated with it.
        """
        self._post_event(9)

    @ZwlrOutputHeadV1.event(
        Argument(ArgumentType.String),
        version=2,
    )
    def make(self, make: str) -> None:
        """Head manufacturer

        This event describes the manufacturer of the head.

        Together with the model and serial_number events the purpose is to
        allow clients to recognize heads from previous sessions and for example
        load head-specific configurations back.

        It is not guaranteed this event will be ever sent. A reason for that
        can be that the compositor does not have information about the make of
        the head or the definition of a make is not sensible in the current
        setup, for example in a virtual session. Clients can still try to
        identify the head by available information from other events but should
        be aware that there is an increased risk of false positives.

        If sent, the make event is sent after a wlr_output_head object is
        created and only sent once per object. The make does not change over
        the lifetime of the wlr_output_head object.

        It is not recommended to display the make string in UI to users. For
        that the string provided by the description event should be preferred.

        :param make:
        :type make:
            `ArgumentType.String`
        """
        self._post_event(10, make)

    @ZwlrOutputHeadV1.event(
        Argument(ArgumentType.String),
        version=2,
    )
    def model(self, model: str) -> None:
        """Head model

        This event describes the model of the head.

        Together with the make and serial_number events the purpose is to allow
        clients to recognize heads from previous sessions and for example load
        head-specific configurations back.

        It is not guaranteed this event will be ever sent. A reason for that
        can be that the compositor does not have information about the model of
        the head or the definition of a model is not sensible in the current
        setup, for example in a virtual session. Clients can still try to
        identify the head by available information from other events but should
        be aware that there is an increased risk of false positives.

        If sent, the model event is sent after a wlr_output_head object is
        created and only sent once per object. The model does not change over
        the lifetime of the wlr_output_head object.

        It is not recommended to display the model string in UI to users. For
        that the string provided by the description event should be preferred.

        :param model:
        :type model:
            `ArgumentType.String`
        """
        self._post_event(11, model)

    @ZwlrOutputHeadV1.event(
        Argument(ArgumentType.String),
        version=2,
    )
    def serial_number(self, serial_number: str) -> None:
        """Head serial number

        This event describes the serial number of the head.

        Together with the make and model events the purpose is to allow clients
        to recognize heads from previous sessions and for example load head-
        specific configurations back.

        It is not guaranteed this event will be ever sent. A reason for that
        can be that the compositor does not have information about the serial
        number of the head or the definition of a serial number is not sensible
        in the current setup. Clients can still try to identify the head by
        available information from other events but should be aware that there
        is an increased risk of false positives.

        If sent, the serial number event is sent after a wlr_output_head object
        is created and only sent once per object. The serial number does not
        change over the lifetime of the wlr_output_head object.

        It is not recommended to display the serial_number string in UI to
        users. For that the string provided by the description event should be
        preferred.

        :param serial_number:
        :type serial_number:
            `ArgumentType.String`
        """
        self._post_event(12, serial_number)

    @ZwlrOutputHeadV1.event(
        Argument(ArgumentType.Uint),
        version=4,
    )
    def adaptive_sync(self, state: int) -> None:
        """Current adaptive sync state

        This event describes whether adaptive sync is currently enabled for the
        head or not. Adaptive sync is also known as Variable Refresh Rate or
        VRR.

        :param state:
        :type state:
            `ArgumentType.Uint`
        """
        self._post_event(13, state)


class ZwlrOutputManagerV1Resource(Resource[ZwlrOutputManagerV1]):
    interface = ZwlrOutputManagerV1

    @ZwlrOutputManagerV1.event(
        Argument(ArgumentType.NewId, interface=ZwlrOutputHeadV1),
    )
    def head(self, head: ZwlrOutputHeadV1) -> None:
        """Introduce a new head

        This event introduces a new head. This happens whenever a new head
        appears (e.g. a monitor is plugged in) or after the output manager is
        bound.

        :param head:
        :type head:
            :class:`~pywayland.protocol.wlr_output_management_unstable_v1.ZwlrOutputHeadV1`
        """
        self._post_event(0, head)

    @ZwlrOutputManagerV1.event(
        Argument(ArgumentType.Uint),
    )
    def done(self, serial: int) -> None:
        """Sent all information about current configuration

        This event is sent after all information has been sent after binding to
        the output manager object and after any subsequent changes. This
        applies to child head and mode objects as well. In other words, this
        event is sent whenever a head or mode is created or destroyed and
        whenever one of their properties has been changed. Not all state is re-
        sent each time the current configuration changes: only the actual
        changes are sent.

        This allows changes to the output configuration to be seen as atomic,
        even if they happen via multiple events.

        A serial is sent to be used in a future create_configuration request.

        :param serial:
            current configuration serial
        :type serial:
            `ArgumentType.Uint`
        """
        self._post_event(1, serial)

    @ZwlrOutputManagerV1.event()
    def finished(self) -> None:
        """The compositor has finished with the manager

        This event indicates that the compositor is done sending manager
        events. The compositor will destroy the object immediately after
        sending this event, so it will become invalid and the client should
        release any resources associated with it.
        """
        self._post_event(2)


class ZwlrOutputModeV1Resource(Resource[ZwlrOutputModeV1]):
    interface = ZwlrOutputModeV1

    @ZwlrOutputModeV1.event(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def size(self, width: int, height: int) -> None:
        """Mode size

        This event describes the mode size. The size is given in physical
        hardware units of the output device. This is not necessarily the same
        as the output size in the global compositor space. For instance, the
        output may be scaled or transformed.

        :param width:
            width of the mode in hardware units
        :type width:
            `ArgumentType.Int`
        :param height:
            height of the mode in hardware units
        :type height:
            `ArgumentType.Int`
        """
        self._post_event(0, width, height)

    @ZwlrOutputModeV1.event(
        Argument(ArgumentType.Int),
    )
    def refresh(self, refresh: int) -> None:
        """Mode refresh rate

        This event describes the mode's fixed vertical refresh rate. It is only
        sent if the mode has a fixed refresh rate.

        :param refresh:
            vertical refresh rate in mHz
        :type refresh:
            `ArgumentType.Int`
        """
        self._post_event(1, refresh)

    @ZwlrOutputModeV1.event()
    def preferred(self) -> None:
        """Mode is preferred

        This event advertises this mode as preferred.
        """
        self._post_event(2)

    @ZwlrOutputModeV1.event()
    def finished(self) -> None:
        """The mode has disappeared

        This event indicates that the mode is no longer available. The mode
        object becomes inert. Clients should send a destroy request and release
        any resources associated with it.
        """
        self._post_event(3)


class ZwlrOutputConfigurationHeadV1Proxy(Proxy[ZwlrOutputConfigurationHeadV1]):
    interface = ZwlrOutputConfigurationHeadV1

    @ZwlrOutputConfigurationHeadV1.request(
        Argument(ArgumentType.Object, interface=ZwlrOutputModeV1),
    )
    def set_mode(self, mode: ZwlrOutputModeV1Proxy) -> None:
        """Set the mode

        This request sets the head's mode.

        :param mode:
        :type mode:
            :class:`~pywayland.protocol.wlr_output_management_unstable_v1.ZwlrOutputModeV1`
        """
        self._marshal(0, mode)

    @ZwlrOutputConfigurationHeadV1.request(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def set_custom_mode(self, width: int, height: int, refresh: int) -> None:
        """Set a custom mode

        This request assigns a custom mode to the head. The size is given in
        physical hardware units of the output device. If set to zero, the
        refresh rate is unspecified.

        It is a protocol error to set both a mode and a custom mode.

        :param width:
            width of the mode in hardware units
        :type width:
            `ArgumentType.Int`
        :param height:
            height of the mode in hardware units
        :type height:
            `ArgumentType.Int`
        :param refresh:
            vertical refresh rate in mHz or zero
        :type refresh:
            `ArgumentType.Int`
        """
        self._marshal(1, width, height, refresh)

    @ZwlrOutputConfigurationHeadV1.request(
        Argument(ArgumentType.Int),
        Argument(ArgumentType.Int),
    )
    def set_position(self, x: int, y: int) -> None:
        """Set the position

        This request sets the head's position in the global compositor space.

        :param x:
            x position in the global compositor space
        :type x:
            `ArgumentType.Int`
        :param y:
            y position in the global compositor space
        :type y:
            `ArgumentType.Int`
        """
        self._marshal(2, x, y)

    @ZwlrOutputConfigurationHeadV1.request(
        Argument(ArgumentType.Int),
    )
    def set_transform(self, transform: int) -> None:
        """Set the transform

        This request sets the head's transform.

        :param transform:
        :type transform:
            `ArgumentType.Int`
        """
        self._marshal(3, transform)

    @ZwlrOutputConfigurationHeadV1.request(
        Argument(ArgumentType.Fixed),
    )
    def set_scale(self, scale: float) -> None:
        """Set the scale

        This request sets the head's scale.

        :param scale:
        :type scale:
            `ArgumentType.Fixed`
        """
        self._marshal(4, scale)

    @ZwlrOutputConfigurationHeadV1.request(
        Argument(ArgumentType.Uint),
        version=4,
    )
    def set_adaptive_sync(self, state: int) -> None:
        """Enable/disable adaptive sync

        This request enables/disables adaptive sync. Adaptive sync is also
        known as Variable Refresh Rate or VRR.

        :param state:
        :type state:
            `ArgumentType.Uint`
        """
        self._marshal(5, state)


class ZwlrOutputConfigurationV1Proxy(Proxy[ZwlrOutputConfigurationV1]):
    interface = ZwlrOutputConfigurationV1

    @ZwlrOutputConfigurationV1.request(
        Argument(ArgumentType.NewId, interface=ZwlrOutputConfigurationHeadV1),
        Argument(ArgumentType.Object, interface=ZwlrOutputHeadV1),
    )
    def enable_head(self, head: ZwlrOutputHeadV1Proxy) -> ZwlrOutputConfigurationHeadV1Proxy:
        """Enable and configure a head

        Enable a head. This request creates a head configuration object that
        can be used to change the head's properties.

        :param head:
            the head to be enabled
        :type head:
            :class:`~pywayland.protocol.wlr_output_management_unstable_v1.ZwlrOutputHeadV1`
        :returns:
            :class:`~pywayland.protocol.wlr_output_management_unstable_v1.ZwlrOutputConfigurationHeadV1`
            -- a new object to configure the head
        """
        id = self._marshal_constructor(0, ZwlrOutputConfigurationHeadV1, head)
        return id

    @ZwlrOutputConfigurationV1.request(
        Argument(ArgumentType.Object, interface=ZwlrOutputHeadV1),
    )
    def disable_head(self, head: ZwlrOutputHeadV1Proxy) -> None:
        """Disable a head

        Disable a head.

        :param head:
            the head to be disabled
        :type head:
            :class:`~pywayland.protocol.wlr_output_management_unstable_v1.ZwlrOutputHeadV1`
        """
        self._marshal(1, head)

    @ZwlrOutputConfigurationV1.request()
    def apply(self) -> None:
        """Apply the configuration

        Apply the new output configuration.

        In case the configuration is successfully applied, there is no
        guarantee that the new output state matches completely the requested
        configuration. For instance, a compositor might round the scale if it
        doesn't support fractional scaling.

        After this request has been sent, the compositor must respond with an
        succeeded, failed or cancelled event. Sending a request that isn't the
        destructor is a protocol error.
        """
        self._marshal(2)

    @ZwlrOutputConfigurationV1.request()
    def test(self) -> None:
        """Test the configuration

        Test the new output configuration. The configuration won't be applied,
        but will only be validated.

        Even if the compositor succeeds to test a configuration, applying it
        may fail.

        After this request has been sent, the compositor must respond with an
        succeeded, failed or cancelled event. Sending a request that isn't the
        destructor is a protocol error.
        """
        self._marshal(3)

    @ZwlrOutputConfigurationV1.request()
    def destroy(self) -> None:
        """Destroy the output configuration

        Using this request a client can tell the compositor that it is not
        going to use the configuration object anymore. Any changes to the
        outputs that have not been applied will be discarded.

        This request also destroys wlr_output_configuration_head objects
        created via this object.
        """
        self._marshal(4)
        self._destroy()


class ZwlrOutputHeadV1Proxy(Proxy[ZwlrOutputHeadV1]):
    interface = ZwlrOutputHeadV1

    @ZwlrOutputHeadV1.request(version=3)
    def release(self) -> None:
        """Destroy the head object

        This request indicates that the client will no longer use this head
        object.
        """
        self._marshal(0)
        self._destroy()


class ZwlrOutputManagerV1Proxy(Proxy[ZwlrOutputManagerV1]):
    interface = ZwlrOutputManagerV1

    @ZwlrOutputManagerV1.request(
        Argument(ArgumentType.NewId, interface=ZwlrOutputConfigurationV1),
        Argument(ArgumentType.Uint),
    )
    def create_configuration(self, serial: int) -> ZwlrOutputConfigurationV1Proxy:
        """Create a new output configuration object

        Create a new output configuration object. This allows to update head
        properties.

        :param serial:
        :type serial:
            `ArgumentType.Uint`
        :returns:
            :class:`~pywayland.protocol.wlr_output_management_unstable_v1.ZwlrOutputConfigurationV1`
        """
        id = self._marshal_constructor(0, ZwlrOutputConfigurationV1, serial)
        return id

    @ZwlrOutputManagerV1.request()
    def stop(self) -> None:
        """Stop sending events

        Indicates the client no longer wishes to receive events for output
        configuration changes. However the compositor may emit further events,
        until the finished event is emitted.

        The client must not send any more requests after this one.
        """
        self._marshal(1)


class ZwlrOutputModeV1Proxy(Proxy[ZwlrOutputModeV1]):
    interface = ZwlrOutputModeV1

    @ZwlrOutputModeV1.request(version=3)
    def release(self) -> None:
        """Destroy the mode object

        This request indicates that the client will no longer use this mode
        object.
        """
        self._marshal(0)
        self._destroy()


class ZwlrOutputConfigurationHeadV1Global(Global[ZwlrOutputConfigurationHeadV1]):
    interface = ZwlrOutputConfigurationHeadV1


class ZwlrOutputConfigurationV1Global(Global[ZwlrOutputConfigurationV1]):
    interface = ZwlrOutputConfigurationV1


class ZwlrOutputHeadV1Global(Global[ZwlrOutputHeadV1]):
    interface = ZwlrOutputHeadV1


class ZwlrOutputManagerV1Global(Global[ZwlrOutputManagerV1]):
    interface = ZwlrOutputManagerV1


class ZwlrOutputModeV1Global(Global[ZwlrOutputModeV1]):
    interface = ZwlrOutputModeV1


ZwlrOutputConfigurationHeadV1._gen_c()
ZwlrOutputConfigurationHeadV1.proxy_class = ZwlrOutputConfigurationHeadV1Proxy
ZwlrOutputConfigurationHeadV1.resource_class = ZwlrOutputConfigurationHeadV1Resource
ZwlrOutputConfigurationHeadV1.global_class = ZwlrOutputConfigurationHeadV1Global


ZwlrOutputConfigurationV1._gen_c()
ZwlrOutputConfigurationV1.proxy_class = ZwlrOutputConfigurationV1Proxy
ZwlrOutputConfigurationV1.resource_class = ZwlrOutputConfigurationV1Resource
ZwlrOutputConfigurationV1.global_class = ZwlrOutputConfigurationV1Global


ZwlrOutputHeadV1._gen_c()
ZwlrOutputHeadV1.proxy_class = ZwlrOutputHeadV1Proxy
ZwlrOutputHeadV1.resource_class = ZwlrOutputHeadV1Resource
ZwlrOutputHeadV1.global_class = ZwlrOutputHeadV1Global


ZwlrOutputManagerV1._gen_c()
ZwlrOutputManagerV1.proxy_class = ZwlrOutputManagerV1Proxy
ZwlrOutputManagerV1.resource_class = ZwlrOutputManagerV1Resource
ZwlrOutputManagerV1.global_class = ZwlrOutputManagerV1Global


ZwlrOutputModeV1._gen_c()
ZwlrOutputModeV1.proxy_class = ZwlrOutputModeV1Proxy
ZwlrOutputModeV1.resource_class = ZwlrOutputModeV1Resource
ZwlrOutputModeV1.global_class = ZwlrOutputModeV1Global
